### ISSUE TITLE
Starttime of TimePicker no set to current time

### ISSUE THREAD

**Issue by ITServicesAM** [davecoffin/nativescript-modal-datetimepicker#5]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
- Android 
- Android Version 7.0
- device

### Please, provide the following version numbers that your issue occurs with:

- CLI: (run `tns --version` to fetch it) 3.3.0
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project) 3.3.0
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the `package.json` file of your project) 3.3.1
- Plugin(s): (look for the version numbers in the `package.json` file of your
project and paste your dependencies and devDependencies here)
"dependencies": {
    "@angular/animations": "4.4.6",
    "@angular/common": "4.4.6",
    "@angular/compiler": "4.4.6",
    "@angular/core": "4.4.6",
    "@angular/forms": "4.4.6",
    "@angular/http": "4.4.6",
    "@angular/platform-browser": "4.4.6",
    "@angular/router": "4.4.6",
    "moment": "^2.19.3",
    "nativescript-angular": "4.4.1",
    "nativescript-cardview": "^2.0.4",
    "nativescript-fancyalert": "^1.1.2",
    "nativescript-loading-indicator": "^2.4.0",
    "nativescript-material-icons": "^1.0.3",
    "nativescript-modal-datetimepicker": "^1.0.3",
    "nativescript-ngx-fonticon": "^4.0.0",
    "nativescript-plugin-firebase": "5.0.2",
    "nativescript-ripple": "^2.0.0",
    "nativescript-theme-core": "1.0.4",
    "reflect-metadata": "0.1.10",
    "rxjs": "5.5.2",
    "tns-core-modules": "3.3.0",
    "zone.js": "0.8.18"
  },
  "devDependencies": {
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "lazy": "1.0.11",
    "nativescript-dev-sass": "^1.3.5",
    "nativescript-dev-typescript": "0.5.1",
    "typescript": "2.4.2"
  },

### Please, tell us how to recreate the issue in as much detail as possible. 
Just launch the timePickerDialog and the shown time is not set to the current time

**Comment by DenizenB** [comment]
I'm experiencing the same issue; whenever the time dialog is opened on Android (8.0), the time is set to 11:12 instead of the current time. This happens for both the 12h and 24h modes.

I tried forking and calling the TimePickerDialog.updateTime method before showing the dialog, but that had no effect. Not sure what the issue could be.

**Comment by jogboms** [comment]
@SomewhatDisoriented  It is caused by the line.
https://github.com/davecoffin/nativescript-modal-datetimepicker/blob/16a62116ad1ba8b79f92996955df632fc8cf1619/src/modal-datetimepicker.android.ts#L111

@davecoffin I wonder if we could `startingHour` and `startingMinute` as parameters to determine what hour/minute you want to set which would otherwise default to the calendar's.

**Comment by shiv19** [comment]
Published as v1.1.0

**Comment by jogboms** [comment]
Thanks @shiv19 👌

**Comment by shiv19** [comment]
You are welcome ^_^
